[package]
name = "interpreter-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [lib]
# src = "src/lib.rs"

# [[bin]]
# src = "src/main.rs"

[dependencies]
